apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/prometheus-operator/prometheus-operator?ref=v0.42.1
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - prometheus.yaml