apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana
spec:
  replicas: 1
  serviceName: grafana
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
        - image: grafana/grafana:7.1.5
          name: grafana
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: data
            - mountPath: /etc/grafana/provisioning/datasources
              name: datasources
              readOnly: true
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
      securityContext:
        runAsUser: 472
        fsGroup: 472
      volumes:
        - name: datasources
          configMap:
            name: grafana
            items:
              - key: grafana-datasources.yml
                path: main.yml
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi