apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:
  grafana-datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Self Monitoring
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus-operated:9090/
