apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-metrics-exporter
  labels:
    app.kubernetes.io/name: kube-metrics-exporter
spec:
  replicas: 1
  template:
    metadata:
      name: kube-metrics-exporter
      labels:
        app.kubernetes.io/name: kube-metrics-exporter
        prometheus/scrape-type: metrics
    spec:
      containers:
        - name: kube-metrics-exporter
          image: itzg/kube-metrics-exporter:v1.0.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              name: scrape
      serviceAccountName: kube-metrics-monitor
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-metrics-exporter
